version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    env_file: .env
    container_name: postgres-d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./infra/postgres/db_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    tty: true