version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    env_file: .env
    container_name: postgres-d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./infra/postgres/db_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    tty: true
  minio:
    image: quay.io/minio/minio
    restart: always
    env_file: .env
    container_name: minio-d
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./infra/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=http://${HOST}:9000
      - MINIO_BROWSER_REDIRECT_URL=http://${HOST}:9001
    command: server --console-address ":9001" /data
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    env_file: .env
    container_name: clickhouse-d
    ports:
      - "8123:8123"  # HTTP-интерфейс
      - "9002:9000"  # Нативный протокол
    volumes:
      - ./infra/click/data:/var/lib/clickhouse
      - ./infra/click/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-password}